name       : compsize
version    : '1.5'
release    : 2
source     :
    - https://github.com/kilobyte/compsize/archive/v1.5.tar.gz : 8b15b528f6cf95ff99d2ddfd7bce87271fd1356c875e5f5895ed83caf6952535
license    : GPL-2.0-or-later
component  : system.utils
summary    : compsize takes a list of files (given as arguments) on a btrfs filesystem and measures used compression types and effective compression ratio
description: |
    compsize takes a list of files (given as arguments) on a btrfs filesystem and measures used compression types and effective compression ratio, producing a report.
builddeps  :
    - pkgconfig(libbtrfsutil)
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/share/man/man8
    %make_install
